// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorcycleShopMVC.Models;

#nullable disable

namespace MotorcycleShopMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417022226_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotorcyclePart", b =>
                {
                    b.Property<int>("MotorcycleId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.HasKey("MotorcycleId", "PartId");

                    b.ToTable("MotorcyclePart");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brand_name");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.HasKey("BrandId")
                        .HasName("PK__brand__5E5A8E27D6FBE891");

                    b.HasIndex(new[] { "BrandName" }, "UQ__brand__0C0C3B58AC12B969")
                        .IsUnique();

                    b.ToTable("brand");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CartId")
                        .HasName("PK__cart__2EF52A2736B8EABB");

                    b.HasIndex(new[] { "UserId" }, "UQ__cart__B9BE370EEF16442A")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "idx_cart_user");

                    b.ToTable("cart");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("CartItemId")
                        .HasName("PK__cart_ite__5D9A6C6ED6140EC7");

                    b.HasIndex("CartId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("PartId");

                    b.ToTable("cart_item");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Motorcycle", b =>
                {
                    b.Property<int>("MotorcycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotorcycleId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("EngineCapacity")
                        .HasColumnType("int")
                        .HasColumnName("engine_capacity");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQty")
                        .HasColumnType("int")
                        .HasColumnName("stock_qty");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("WarrantyPolicy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("warranty_policy");

                    b.Property<int?>("YearFrom")
                        .HasColumnType("int")
                        .HasColumnName("year_from");

                    b.Property<int?>("YearTo")
                        .HasColumnType("int")
                        .HasColumnName("year_to");

                    b.HasKey("MotorcycleId")
                        .HasName("PK__motorcyc__7340036B1F7C9B32");

                    b.HasIndex("BrandId");

                    b.HasIndex("TypeId");

                    b.ToTable("motorcycle");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F23D1F62F");

                    b.HasIndex("UserId");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Processing")
                        .HasColumnName("order_status");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("payment_status");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shipping_address");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__order__4659622989CB449D");

                    b.HasIndex(new[] { "UserId" }, "idx_order_user");

                    b.ToTable("order");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("OrderItemId")
                        .HasName("PK__order_it__3764B6BC2A1FACB9");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("PartId");

                    b.HasIndex(new[] { "OrderId" }, "idx_orderitem_order");

                    b.ToTable("order_item");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("brand_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("part_name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("WarrantyMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("warranty_months");

                    b.HasKey("PartId")
                        .HasName("PK__part__A0E3FAB8AE85F9B9");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("part");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.PartCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId")
                        .HasName("PK__part_cat__D54EE9B4BB9F450B");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__part_cat__5189E2554497F2DD")
                        .IsUnique();

                    b.ToTable("part_category");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("promotion_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MinOrderValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_order_value");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.HasKey("PromotionId")
                        .HasName("PK__promotio__2CB9556B251A8A0D");

                    b.HasIndex(new[] { "Code" }, "UQ__promotio__357D4CF9CDF8E738")
                        .IsUnique();

                    b.ToTable("promotion");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__review__60883D90AA4CCE2F");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("review");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.ReviewImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_path");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.HasKey("ImageId")
                        .HasName("PK__review_i__DC9AC955651A6002");

                    b.HasIndex("ReviewId");

                    b.ToTable("review_image");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("customer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F3F46CAE1");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__users__A1936A6BBF9DED3A")
                        .IsUnique()
                        .HasFilter("[phone_number] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164759D06FA")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.VehicleType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId")
                        .HasName("PK__vehicle___2C000598AB825BDC");

                    b.HasIndex(new[] { "TypeName" }, "UQ__vehicle___543C4FD973271E93")
                        .IsUnique();

                    b.ToTable("vehicle_type");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wishlist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime?>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    b.Property<int?>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId")
                        .HasName("PK__wishlist__6151514E992593C9");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("wishlist");
                });

            modelBuilder.Entity("PartMotorcycle", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("int")
                        .HasColumnName("part_id");

                    b.Property<int>("MotorcycleId")
                        .HasColumnType("int")
                        .HasColumnName("motorcycle_id");

                    b.HasKey("PartId", "MotorcycleId")
                        .HasName("PK__part_mot__07D7FA8E3F4FEAC2");

                    b.HasIndex("MotorcycleId");

                    b.ToTable("part_motorcycle", (string)null);
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Cart", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("MotorcycleShopMVC.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cart__user_id__6FE99F9F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.CartItem", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__cart_item__cart___73BA3083");

                    b.HasOne("MotorcycleShopMVC.Models.Motorcycle", "Motorcycle")
                        .WithMany("CartItems")
                        .HasForeignKey("MotorcycleId")
                        .HasConstraintName("FK__cart_item__motor__74AE54BC");

                    b.HasOne("MotorcycleShopMVC.Models.Part", "Part")
                        .WithMany("CartItems")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__cart_item__part___75A278F5");

                    b.Navigation("Cart");

                    b.Navigation("Motorcycle");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Motorcycle", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Brand", "Brand")
                        .WithMany("Motorcycles")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__motorcycl__brand__5AEE82B9");

                    b.HasOne("MotorcycleShopMVC.Models.VehicleType", "Type")
                        .WithMany("Motorcycles")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__motorcycl__type___5BE2A6F2");

                    b.Navigation("Brand");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Notification", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__notificat__user___22751F6C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Order", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__order__user_id__00200768");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.OrderItem", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Motorcycle", "Motorcycle")
                        .WithMany("OrderItems")
                        .HasForeignKey("MotorcycleId")
                        .HasConstraintName("FK__order_ite__motor__03F0984C");

                    b.HasOne("MotorcycleShopMVC.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__order_ite__order__02FC7413");

                    b.HasOne("MotorcycleShopMVC.Models.Part", "Part")
                        .WithMany("OrderItems")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__order_ite__part___04E4BC85");

                    b.Navigation("Motorcycle");

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Part", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Brand", "Brand")
                        .WithMany("Parts")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK__part__brand_id__66603565");

                    b.HasOne("MotorcycleShopMVC.Models.PartCategory", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__part__category_i__656C112C");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Review", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Motorcycle", "Motorcycle")
                        .WithMany("Reviews")
                        .HasForeignKey("MotorcycleId")
                        .HasConstraintName("FK__review__motorcyc__0C85DE4D");

                    b.HasOne("MotorcycleShopMVC.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__review__order_id__0B91BA14");

                    b.HasOne("MotorcycleShopMVC.Models.Part", "Part")
                        .WithMany("Reviews")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__review__part_id__0D7A0286");

                    b.HasOne("MotorcycleShopMVC.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__review__user_id__0A9D95DB");

                    b.Navigation("Motorcycle");

                    b.Navigation("Order");

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.ReviewImage", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__review_im__revie__114A936A");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Wishlist", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Motorcycle", "Motorcycle")
                        .WithMany("Wishlists")
                        .HasForeignKey("MotorcycleId")
                        .HasConstraintName("FK__wishlist__motorc__1BC821DD");

                    b.HasOne("MotorcycleShopMVC.Models.Part", "Part")
                        .WithMany("Wishlists")
                        .HasForeignKey("PartId")
                        .HasConstraintName("FK__wishlist__part_i__1CBC4616");

                    b.HasOne("MotorcycleShopMVC.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__wishlist__user_i__1AD3FDA4");

                    b.Navigation("Motorcycle");

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PartMotorcycle", b =>
                {
                    b.HasOne("MotorcycleShopMVC.Models.Motorcycle", null)
                        .WithMany()
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__part_moto__motor__6A30C649");

                    b.HasOne("MotorcycleShopMVC.Models.Part", null)
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__part_moto__part___693CA210");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Brand", b =>
                {
                    b.Navigation("Motorcycles");

                    b.Navigation("Parts");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Motorcycle", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Part", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("MotorcycleShopMVC.Models.VehicleType", b =>
                {
                    b.Navigation("Motorcycles");
                });
#pragma warning restore 612, 618
        }
    }
}
